"""empty message

Revision ID: 930d7ba48ea9
Revises: 
Create Date: 2026-04-02 17:50:36.412061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930d7ba48ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_list',
    sa.Column('propertyid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('ptype', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('disc', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('propertyid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_list')
    # ### end Alembic commands ###
